version: '3.8'
services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - moodle_data:/var/www/html/moodle
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass MYSQL_DATABASE=moodle MYSQL_USER=moodleuser MYSQL_PASSWORD=moodlepass
    volumes:
      - db_data:/var/lib/mysql
volumes:
  moodle_data:
  db_data:
